### ISSUE TITLE
"Camera transform" matrix

### ISSUE THREAD

**Issue by xheon** [google-research/corenet#3]
Hi, thanks for the great work and detailed documentation.

While checking the data, I was wondering how the "camera_transform" is chosen and what's the purpose of the homogeneous part.

I understand that the 3x3 part of the 4x4 matrix is the FOV, but what is the purpose of the 4th column
[-0.8660, 0.8660, 0.8664, 0.8666]?

Thanks a lot!

**Comment by vitaminSP** [comment]
Hi Manuel,

Could you take another look at the coordinate systems [documentation](https://github.com/google-research/corenet/blob/main/doc/data_format_and_coordinate_systems.md)? I updated it to explain this.
In short, `camera_transform` is a combination of `look_at` and `perspective_projection`.

Best,
Stefan

**Comment by xheon** [comment]
Thanks a lot, Stefan!
