### ISSUE TITLE
How to get "mesh_visible_fractions"

### ISSUE THREAD

**Issue by njfugit** [google-research/corenet#5]
Hi,
After reading the Data formats and coordinate systems document. I want to know how the value of "mesh_visible_fractions" mentioned in "Scene fields" is obtained. thanks.

**Comment by vitaminSP** [comment]
Hi,
`mesh_visible_fractions` is computed as the number of pixels in the modal mask of each object divided by the number of pixels in its amodal mask.

**Comment by njfugit** [comment]
> Hi, `mesh_visible_fractions` is computed as the number of pixels in the modal mask of each object divided by the number of pixels in its amodal mask.

I have solved it, thanks
